load("@rules_jvm_external//:defs.bzl", "artifact")
load("//java:defs.bzl", "java_library")

java_library(
    name = "httpd",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/src/org/openqa/selenium/grid:__subpackages__",
        "//java/test/org/openqa/selenium/grid:__subpackages__",
    ],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/cli",
        "//java/src/org/openqa/selenium/grid:base-command",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/gateway",
        "//java/src/org/openqa/selenium/grid/graphql",
        "//java/src/org/openqa/selenium/grid/log",
        "//java/src/org/openqa/selenium/grid/security",
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/grid/web",
        "//java/src/org/openqa/selenium/netty/server",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/http",
        artifact("com.beust:jcommander"),
        artifact("com.google.auto.service:auto-service-annotations"),
        artifact("com.google.guava:guava"),
    ],
)
